email:
  on_success: change
  on_failure: always
language: rust
env: # required for allow_failures

# Recommended caching strategy from https://levans.fr/rust_travis_cache.html
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  include:
    - rust: stable
      env: NAME='linting'
      before_script:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cargo fmt --all -- --check
        - cargo clippy

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install sdl2; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt-get install -y libsdl2-dev libegl1-mesa-dev libgles2-mesa-dev; fi

script: |
  export RUST_BACKTRACE=1 &&
  cargo build --verbose &&
  cargo test --verbose &&
  cargo doc --no-deps --verbose
