email:
  on_success: change
  on_failure: always
language: rust
cache: cargo
env: # required for allow_failures
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    #- env: NAME='cargo-travis'
    #- rust: nightly
  include:
    - rust: nightly
      env: NAME='cargo-clippy'
      before_script:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cargo fmt --all -- --check
        - cargo clippy

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install sdl2; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then sudo apt-get install -y libsdl2-dev libegl1-mesa-dev libgles2-mesa-dev; fi

script: |
  export RUST_BACKTRACE=1 &&
  cargo build --verbose &&
  cargo test --verbose &&
  cargo doc --no-deps --verbose
